version: '3.3'
services:
    db:
      image: postgres:11
      environment:
        - "POSTGRES_PASSWORD=postgres"
        - "POSTGRES_USER=postgres"
      ports:
        - '5432:5432'
      volumes:
        - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: