version: '3.7'
services:
  db:
    image: postgres:11
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /book_hub/manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/book_hub
    ports:
     - 8000:8000
    depends_on:
     - db
volumes:
  postgres_data: